In [2]:
import numpy as np

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
pd.read_csv("data.csv")

Country   Age   Salary Purchased
0  Turkey  40.0  72000.0        No
1     USA  27.0  48000.0       Yes
2   Japan  30.0  54000.0        No
3     USA  38.0  61000.0        No
4  Turkey  40.0      NaN       Yes
5  Turkey  35.0  58000.0       Yes
6   Japan   NaN  52000.0        No
7     USA  48.0  79000.0       Yes
8  Turkey  50.0  83000.0        No
9   Japan  37.0  67000.0       Yes

In [5]:
data=pd.read_csv("data.csv")

In [6]:
X=data.iloc[:,:-1]

In [7]:
y=data.iloc[:,3:4]

In [8]:
X

Country   Age   Salary
0  Turkey  40.0  72000.0
1     USA  27.0  48000.0
2   Japan  30.0  54000.0
3     USA  38.0  61000.0
4  Turkey  40.0      NaN
5  Turkey  35.0  58000.0
6   Japan   NaN  52000.0
7     USA  48.0  79000.0
8  Turkey  50.0  83000.0
9   Japan  37.0  67000.0

In [9]:
y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [10]:
X=X.values

In [11]:
X

array([['Turkey', 40.0, 72000.0],
       ['USA', 27.0, 48000.0],
       ['Japan', 30.0, 54000.0],
       ['USA', 38.0, 61000.0],
       ['Turkey', 40.0, nan],
       ['Turkey', 35.0, 58000.0],
       ['Japan', nan, 52000.0],
       ['USA', 48.0, 79000.0],
       ['Turkey', 50.0, 83000.0],
       ['Japan', 37.0, 67000.0]], dtype=object)

In [12]:
y=y.values

In [13]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

## now we can work on missing values

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

### we create a imputer value that helps to change the nan value to rows' mean

In [16]:
imputer.fit(X[:,1:3])

SimpleImputer()

In [17]:
X[:,1:3] = imputer.transform(X[:,1:3])
X

array([['Turkey', 40.0, 72000.0],
       ['USA', 27.0, 48000.0],
       ['Japan', 30.0, 54000.0],
       ['USA', 38.0, 61000.0],
       ['Turkey', 40.0, 63777.77777777778],
       ['Turkey', 35.0, 58000.0],
       ['Japan', 38.333333333333336, 52000.0],
       ['USA', 48.0, 79000.0],
       ['Turkey', 50.0, 83000.0],
       ['Japan', 37.0, 67000.0]], dtype=object)

#### now we change the nan values with the rows mean

# One Hot Encoding (the method encode the string data with machine)

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [19]:
?ColumnTransformer

Init signature:
ColumnTransformer(
    transformers,
    *,
    remainder='drop',
    sparse_threshold=0.3,
    n_jobs=None,
    transformer_weights=None,
    verbose=False,
    verbose_feature_names_out=True,
)
Docstring:     
Applies transformers to columns of an array or pandas DataFrame.

This estimator allows different columns or column subsets of the input
to be transformed separately and the features generated by each transformer
will be concatenated to form a single feature space.
This is useful for heterogeneous or columnar data, to combine several
feature extraction mechanisms or transformations into a single transformer.

Read more in the :ref:`User Guide <column_transformer>`.

.. versionadded:: 0.20

Parameters
----------
transformers : list of tuples
    List of (name, transformer, columns) tuples specifying the
    transformer objects to be applied to subsets of the data.

    name : str
        Like in Pipeline and FeatureUnion, this allows the transformer and
        i

In [20]:
coltrans = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])],remainder="passthrough")

In [21]:
X = np.array(coltrans.fit_transform(X))

In [22]:
X

array([[0.0, 1.0, 0.0, 40.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 38.333333333333336, 52000.0],
       [0.0, 0.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

## if we use drop instead of passthrough we drop all other rows other than we work on it

# Label Encoding (change the variables to label 0 for no, label 1 for yes)

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
?LabelEncoder

Init signature: LabelEncoder()
Docstring:     
Encode target labels with value between 0 and n_classes-1.

This transformer should be used to encode target values, *i.e.* `y`, and
not the input `X`.

Read more in the :ref:`User Guide <preprocessing_targets>`.

.. versionadded:: 0.12

Attributes
----------
classes_ : ndarray of shape (n_classes,)
    Holds the label for each class.

See Also
--------
OrdinalEncoder : Encode categorical features using an ordinal encoding
    scheme.
OneHotEncoder : Encode categorical features as a one-hot numeric array.

Examples
--------
`LabelEncoder` can be used to normalize labels.

>>> from sklearn import preprocessing
>>> le = preprocessing.LabelEncoder()
>>> le.fit([1, 2, 2, 6])
LabelEncoder()
>>> le.classes_
array([1, 2, 6])
>>> le.transform([1, 1, 2, 6])
array([0, 0, 1, 2]...)
>>> le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])

It can also be used to transform non-numerical labels (as long as they are
hashable and comparable) to numerica

In [25]:
labenc = LabelEncoder()

In [26]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [29]:
y = labenc.fit_transform(y)

In [30]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

# Train and Test Sets

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
?train_test_split

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

trai

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [34]:
X_train

array([[1.0, 0.0, 0.0, 38.333333333333336, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 40.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 35.0, 58000.0]], dtype=object)

In [35]:
X_test

array([[1.0, 0.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [36]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1], dtype=int64)

In [37]:
y_test

array([0, 1], dtype=int64)

## train and test functions make the machine learn before the predict

### now we can make predict environment for machine

# Feature Scaling

### standardization

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
stdscl = StandardScaler()

In [40]:
X_train[:,3:]

array([[38.333333333333336, 52000.0],
       [40.0, 63777.77777777778],
       [40.0, 72000.0],
       [38.0, 61000.0],
       [27.0, 48000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [35.0, 58000.0]], dtype=object)

In [41]:
X_train[:,3:]=stdscl.fit_transform(X_train[:,3:])

In [42]:
X_train[:,3:]

array([[-0.17935780752172312, -1.0781259408412425],
       [0.06803227181858379, -0.07013167641635372],
       [0.06803227181858379, 0.633562432710455],
       [-0.22883582338978492, -0.30786617274297867],
       [-1.861610347035813, -1.420463615551582],
       [1.2555046526520586, 1.232653363453549],
       [1.5523727478604274, 1.5749910381638885],
       [-0.674137966202338, -0.5646194287757332]], dtype=object)

In [43]:
X_test[:,3:]=stdscl.transform(X_test[:,3:])

In [44]:
X_test

array([[1.0, 0.0, 0.0, -1.4163082042232598, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.3772698709939693, 0.2056403393225306]],
      dtype=object)

In [45]:
X_train

array([[1.0, 0.0, 0.0, -0.17935780752172312, -1.0781259408412425],
       [0.0, 1.0, 0.0, 0.06803227181858379, -0.07013167641635372],
       [0.0, 1.0, 0.0, 0.06803227181858379, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.22883582338978492, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.861610347035813, -1.420463615551582],
       [0.0, 0.0, 1.0, 1.2555046526520586, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.5523727478604274, 1.5749910381638885],
       [0.0, 1.0, 0.0, -0.674137966202338, -0.5646194287757332]],
      dtype=object)

In [ ]:
### make the numbers meaningfull for machine no matter how big or small they